'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;configuration&gt;
        '''    &lt;startup&gt; 
        '''        &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.5&quot; /&gt;
        '''    &lt;/startup&gt;
        '''&lt;/configuration&gt;.
        '''</summary>
        Friend ReadOnly Property appconfig() As String
            Get
                Return ResourceManager.GetString("appconfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to using System.Reflection;
        '''using System.Runtime.CompilerServices;
        '''using System.Runtime.InteropServices;
        '''
        '''// General Information about an assembly is controlled through the following 
        '''// set of attributes. Change these attribute values to modify the information
        '''// associated with an assembly.
        '''[assembly: AssemblyTitle(&quot;cons&quot;)]
        '''[assembly: AssemblyDescription(&quot;&quot;)]
        '''[assembly: AssemblyConfiguration(&quot;&quot;)]
        '''[assembly: AssemblyCompany(&quot;&quot;)]
        '''[assembly: AssemblyProduct(&quot;cons&quot;)]
        '''[assembly: AssemblyCopyright(&quot;Cop [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property assemblyinfo() As String
            Get
                Return ResourceManager.GetString("assemblyinfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;Project ToolsVersion=&quot;12.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        '''  &lt;Import Project=&quot;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&quot; Condition=&quot;Exists(&apos;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&apos;)&quot; /&gt;
        '''  &lt;PropertyGroup&gt;
        '''    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        '''    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        '''    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property conscsproj() As String
            Get
                Return ResourceManager.GetString("conscsproj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to using System;
        '''using System.Collections.Generic;
        '''using System.Linq;
        '''using System.Security.Cryptography;
        '''using System.Text;
        '''using System.Threading.Tasks;
        '''using System.Windows.Forms;
        '''
        '''namespace cons
        '''{
        '''    static class Program
        '''    {
        '''        /// &lt;summary&gt;
        '''        /// The main entry point for the application.
        '''        /// &lt;/summary&gt;
        '''        [STAThread]
        '''        static void Main()
        '''        {
        '''            string anonstring = &quot;manchester&quot;;
        '''            byte[] b = Convert.FromBase64String(anonstring);
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property dllclass() As String
            Get
                Return ResourceManager.GetString("dllclass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to //------------------------------------------------------------------------------
        '''// &lt;auto-generated&gt;
        '''//     This code was generated by a tool.
        '''//     Runtime Version:4.0.30319.42000
        '''//
        '''//     Changes to this file may cause incorrect behavior and will be lost if
        '''//     the code is regenerated.
        '''// &lt;/auto-generated&gt;
        '''//------------------------------------------------------------------------------
        '''
        '''namespace cons.Properties
        '''{
        '''
        '''
        '''    /// &lt;summary&gt;
        '''    ///   A strongly-typed resource class, for looki [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property recourcesdesigner() As String
            Get
                Return ResourceManager.GetString("recourcesdesigner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;root&gt;
        '''  &lt;!-- 
        '''    Microsoft ResX Schema 
        '''    
        '''    Version 2.0
        '''    
        '''    The primary goals of this format is to allow a simple XML format 
        '''    that is mostly human readable. The generation and parsing of the 
        '''    various data types are done through the TypeConverter classes 
        '''    associated with the data types.
        '''    
        '''    Example:
        '''    
        '''    ... ado.net/XML headers &amp; schema ...
        '''    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        '''    &lt;resheader n [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property resour() As String
            Get
                Return ResourceManager.GetString("resour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        '''&lt;SettingsFile xmlns=&quot;http://schemas.microsoft.com/VisualStudio/2004/01/settings&quot; CurrentProfile=&quot;(Default)&quot;&gt;
        '''  &lt;Profiles&gt;
        '''    &lt;Profile Name=&quot;(Default)&quot; /&gt;
        '''  &lt;/Profiles&gt;
        '''  &lt;Settings /&gt;
        '''&lt;/SettingsFile&gt;.
        '''</summary>
        Friend ReadOnly Property settings() As String
            Get
                Return ResourceManager.GetString("settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to //------------------------------------------------------------------------------
        '''// &lt;auto-generated&gt;
        '''//     This code was generated by a tool.
        '''//     Runtime Version:4.0.30319.42000
        '''//
        '''//     Changes to this file may cause incorrect behavior and will be lost if
        '''//     the code is regenerated.
        '''// &lt;/auto-generated&gt;
        '''//------------------------------------------------------------------------------
        '''
        '''namespace cons.Properties
        '''{
        '''
        '''
        '''    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property settingsdesigner() As String
            Get
                Return ResourceManager.GetString("settingsdesigner", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
